[package]
authors = ["Marcos Gutiérrez Alonso <margual56@gmail.com>"]
description = "A simple radio cli for listening to your favourite streams from the console"
name = "radio-cli"
version = "0.2.0"
edition = "2021"
homepage = "https://github.com/margual56/radio-cli"
repository = "https://github.com/margual56/radio-cli.git"
license = "GPL-2"

[dependencies]
structopt = "0.3.26"
serde = {version="^1.0", features = ["derive"]}
serde_json = { version = "^1.0", default-features = false, features = ["alloc"] }
colored = "2"
xdg = "2.4.1" # https://docs.rs/xdg/latest/xdg/struct.BaseDirectories.html
inquire = "0.2.1"

[lib]
path = "src/lib/lib.rs"
name = "radio_libs"
